export interface HouseModel {
  id: number;
  name: string;
  tipologia: string;
  areaBrutaInterior: string;
  areaTotal: string;
  wc: number;
  image: string; // User will add images later
}

export const houseModels: HouseModel[] = [
  {
    id: 1,
    name: "Portland",
    tipologia: "V3",
    areaBrutaInterior: "123m²",
    areaTotal: "228m²",
    wc: 2,
    image: "/plantas/portland-v3.webp",
  },
  {
    id: 2,
    name: "San Diego",
    tipologia: "V3",
    areaBrutaInterior: "114m²",
    areaTotal: "175m²",
    wc: 2,
    image: "/plantas/san-diego-v3.webp",
  },
  {
    id: 3,
    name: "Glasgow",
    tipologia: "V0",
    areaBrutaInterior: "19m²",
    areaTotal: "27m²",
    wc: 1,
    image: "/plantas/glasgow.webp",
  },
  {
    id: 4,
    name: "Vail",
    tipologia: "V2",
    areaBrutaInterior: "60m²",
    areaTotal: "90m²",
    wc: 1,
    image: "/plantas/vail.webp",
  },
  {
    id: 5,
    name: "Ribeira Brava",
    tipologia: "V1",
    areaBrutaInterior: "40m²",
    areaTotal: "50m²",
    wc: 1,
    image: "/plantas/Ribeira-Brava-V1.webp",
  },
  {
    id: 6,
    name: "Phoenix",
    tipologia: "V2",
    areaBrutaInterior: "108m²",
    areaTotal: "177m²",
    wc: 2,
    image: "/plantas/phoenix.webp",
  },
  {
    id: 7,
    name: "Lagos",
    tipologia: "V1",
    areaBrutaInterior: "44m²",
    areaTotal: "55m²",
    wc: 1,
    image: "/plantas/lagos.webp",
  },
  {
    id: 8,
    name: "Mimosa",
    tipologia: "V0",
    areaBrutaInterior: "42m²",
    areaTotal: "56m²",
    wc: 1,
    image: "/plantas/Mimosa-V1.25.webp",
  },
  {
    id: 9,
    name: "Baiona",
    tipologia: "V3",
    areaBrutaInterior: "122m²",
    areaTotal: "158m²",
    wc: 3,
    image: "/plantas/Baiona-V3.25.webp",
  },
  {
    id: 10,
    name: "Long Beach",
    tipologia: "V3",
    areaBrutaInterior: "302m²",
    areaTotal: "403m²",
    wc: 3,
    image: "/plantas/long-beach.webp",
  },
  {
    id: 11,
    name: "Toronto",
    tipologia: "V3",
    areaBrutaInterior: "90m²",
    areaTotal: "123m²",
    wc: 2,
    image: "/plantas/toronto.webp",
  },
  {
    id: 12,
    name: "Aspen",
    tipologia: "V2",
    areaBrutaInterior: "65m²",
    areaTotal: "105m²",
    wc: 1,
    image: "/plantas/aspen.webp",
  },
  {
    id: 13,
    name: "Vermont",
    tipologia: "V1",
    areaBrutaInterior: "69m²",
    areaTotal: "93m²",
    wc: 1,
    image: "/plantas/vermount.webp",
  },
  {
    id: 14,
    name: "Serra da Estrela",
    tipologia: "V2",
    areaBrutaInterior: "65m²",
    areaTotal: "103m²",
    wc: 1,
    image: "/plantas/Serra-da-Estrela-V2.25.webp",
  },
  {
    id: 15,
    name: "Chalé Arrábida",
    tipologia: "V2+1",
    areaBrutaInterior: "70m²",
    areaTotal: "115m²",
    wc: 1,
    image: "/plantas/chale-arrabida.webp",
  },
  {
    id: 16,
    name: "Chalé Gerês",
    tipologia: "V1",
    areaBrutaInterior: "43m²",
    areaTotal: "70m²",
    wc: 1,
    image: "/plantas/chale-geres.webp",
  },
  {
    id: 17,
    name: "Miami",
    tipologia: "V3",
    areaBrutaInterior: "151m²",
    areaTotal: "208m²",
    wc: 3,
    image: "/plantas/Miami-V3.25.webp",
  },
  {
    id: 18,
    name: "Oakland",
    tipologia: "V2",
    areaBrutaInterior: "89m²",
    areaTotal: "137m²",
    wc: 2,
    image: "/plantas/Oakland-V2.25.webp",
  },
  {
    id: 19,
    name: "Riverside",
    tipologia: "V1",
    areaBrutaInterior: "48m²",
    areaTotal: "74m²",
    wc: 1,
    image: "/plantas/Riverside-V1.25.webp",
  },
  {
    id: 20,
    name: "Praga",
    tipologia: "V4",
    areaBrutaInterior: "194m²",
    areaTotal: "286m²",
    wc: 4,
    image: "/plantas/Praga-V4.25-2.webp",
  },
  {
    id: 21,
    name: "Paris",
    tipologia: "V2",
    areaBrutaInterior: "82m²",
    areaTotal: "117m²",
    wc: 2,
    image: "/plantas/Paris-V2.25.webp",
  },
  {
    id: 22,
    name: "Lisboa",
    tipologia: "V2",
    areaBrutaInterior: "87m²",
    areaTotal: "108m²",
    wc: 2,
    image: "/plantas/Lisboa-V2.25.webp",
  },
  {
    id: 23,
    name: "Berlim",
    tipologia: "V3",
    areaBrutaInterior: "128m²",
    areaTotal: "175m²",
    wc: 3,
    image: "/plantas/Berlim-V2.25.webp",
  },
  {
    id: 24,
    name: "Viena",
    tipologia: "V2",
    areaBrutaInterior: "75m²",
    areaTotal: "103m²",
    wc: 2,
    image: "/plantas/Viena-V3.25-2.webp",
  },
  {
    id: 25,
    name: "Madrid",
    tipologia: "V2",
    areaBrutaInterior: "70m²",
    areaTotal: "95m²",
    wc: 2,
    image: "/plantas/Madrid-V2.25.webp",
  },
  {
    id: 26,
    name: "Atenas",
    tipologia: "V2",
    areaBrutaInterior: "84m²",
    areaTotal: "115m²",
    wc: 2,
    image: "/plantas/Atenas-V2.25.webp",
  },
  {
    id: 27,
    name: "Budapeste",
    tipologia: "V2",
    areaBrutaInterior: "83m²",
    areaTotal: "123m²",
    wc: 2,
    image: "/plantas/Budapeste_correct.webp",
  },
  {
    id: 28,
    name: "Mónaco",
    tipologia: "V0",
    areaBrutaInterior: "35m²",
    areaTotal: "50m²",
    wc: 1,
    image: "/plantas/Monaco-V0.25.webp",
  },
  {
    id: 29,
    name: "Oslo",
    tipologia: "V1",
    areaBrutaInterior: "48m²",
    areaTotal: "70m²",
    wc: 1,
    image: "/plantas/Oslo-V1.25-1.webp",
  },
  {
    id: 30,
    name: "Londres",
    tipologia: "V1",
    areaBrutaInterior: "49m²",
    areaTotal: "70m²",
    wc: 1,
    image: "/plantas/Londres-V1.25.webp",
  },
];
